insert into city(name,state) values( 'KC','KS');
insert into city(name,state) values( 'KC','MO');
insert into city(name,state) values( 'Topeka','KS');
insert into city(name,state) values( 'St.Joseph','MO');
insert into city(name,state) values( 'St.Louis','MO');
insert into city(name,state) values( 'Hyderabad','Telangana');
insert into address(id,streetAddr1,streetAddr2,city,state,country,zipcode) values (1,'1 W East St','11 E West St','Kansas City','MO','US',64112);
insert into address(id,streetAddr1,streetAddr2,city,state,country,zipcode) values (2,'2 W East St','22 E West St','Kansas City','MO','US',64112);
insert into address(id,streetAddr1,streetAddr2,city,state,country,zipcode) values (3,'3 W East St','33 E West St','Kansas City','MO','US',64112);
insert into address(id,streetAddr1,streetAddr2,city,state,country,zipcode) values (4,'1 St','11 St','Overland Park','Kansas City','US',66223);
insert into address(id,streetAddr1,streetAddr2,city,state,country,zipcode) values (5,'2 St','22 St','Overland Park','Kansas City','US',66223);
insert into address(id,streetAddr1,streetAddr2,city,state,country,zipcode) values (6,'2 St','33 St','Overland Park','Kansas City','US',66223);
insert into address(id,streetAddr1,streetAddr2,city,state,country,zipcode) values (7,'123 St','99 St','Olathe','KS','US',66223);
insert into address(id,streetAddr1,streetAddr2,city,state,country,zipcode) values (8,'234 St','88 St','Olathe','KS','US',66223);
insert into address(id,streetAddr1,streetAddr2,city,state,country,zipcode) values (9,'345 St','77 St','Olathe','KS','US',66223);
